import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../style/globals.css";
import NextTopLoader from "nextjs-toploader";
import TranstackQueryProvider from "@/providers/transtac-query-provider";
import { Toaster } from "react-hot-toast";
import ReduxProvider from "@/lib/ReuxProvider";
import StoreUser from "@/components/StorUser";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
        {/* tanstack provider */}
        <TranstackQueryProvider>

          {/* redux provider */}
          <ReduxProvider>

            {/* store user */}
            <StoreUser />

            {/* top loader */}
            <NextTopLoader color="blue" />

            {/* toast */}
            <Toaster position="top-center"
              toastOptions={{
                style: {
                  background: '#374151',
                  color: '#fff',
                  fontSize: '14px',
                  borderRadius: '10px',
                  padding: '5px 10px',
                },
              }} />

            {/*  */}
            {children}

          </ReduxProvider>


        </TranstackQueryProvider>
      </body>
    </html>
  );
}
